### ISSUE TITLE
How to prepare config for model searching?

### ISSUE THREAD

**Issue by Catosine** [skmhrk1209/Single-Path-NAS-PyTorch#1]
Hello @skmhrk1209 !

Thanks for your amazing work! 
I want to run your code with my own dataset. And I noticed that your first_order_search.py takes an input variable of "--config", which seems to be a json file.
However, I didn't fount it in your repo. So it is kinda hard for me to figure out how to prepare this config.
Would you mind telling me how to deal with it? Or could you post the config you are using, so I could make my own based on that.

Thanks again for your work!

**Comment by skmhrk1209** [comment]
Hi, thank you for your comment.
I pushed config file now.
Moreover, I modified code to solve single-level optimization problem following the paper. 
If you want to solve bilevel optimization problem like DARTS, you can use the instance methods of SuperMobileNetV2.

**Comment by Catosine** [comment]
@skmhrk1209 Thanks!
