### ISSUE TITLE
Questions regarding ops.py

### ISSUE THREAD

**Issue by Catosine** [skmhrk1209/Single-Path-NAS-PyTorch#2]
Hello @skmhrk1209 

Thanks again for your updates!
I've got some questions to ops.py. The first question is about forward(). I see that your codes will check the norm of each part of the kernels and channels and compare them with the thresholds. However, I was wondering if it is possible to get a "hollow" kernel/channel (i.e. only 5x5\3x3), which I think it is abnormal as a searching result.
The second question is about how to determine the final searched model. I didn't see that part in the existing codes and I am working on that (That's why I have the first question). If it is convenient, could you please share the model-determining part of codes? It is also okay if you could explain the first question to me so I could make my own version of the determining parts.

Thanks!

**Comment by Catosine** [comment]
I re-read your code and got your idea. Thanks

**Comment by Catosine** [comment]
Sorry, I just got your forward idea. But I am still uncertain about how you determine the searched kernel&channel size.

**Comment by skmhrk1209** [comment]
Hi, thanks for your question.
You can determine the kernel by calling SuperMobileNet.freeze_weight(). 
This function freezes kernel using the learned threshold.

**Comment by Catosine** [comment]
Thanks! I actually made my own version of retrieving the searched structure. I will let you know if I found something interesting.
BTW would you mind sharing your searching result?
Thanks again!

**Comment by skmhrk1209** [comment]
Unlike the paper, I haven't considered the device constraints for searching architectures yet.
It may be because of that, I haven't gotten a meaningful result yet. 
If I get a good result, I will share the result!
Thank you.

**Comment by Catosine** [comment]
I see. Thanks!
